name: torn_ticket
description: "A fully customizable torn ticket widget for Flutter applications."
version: 0.0.1
homepage: https://github.com/suhail600/torn_ticket
keywords: [ticket, torn, scratch, coupon, ui, customizable, flutter, dart, widget, design]

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
